# Generated by Django 3.1.6 on 2021-02-06 15:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medical_shop_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
