# Generated by Django 3.1.6 on 2021-02-06 15:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('medical_shop_app', '0002_auto_20210206_2048'),
    ]

    operations = [
        migrations.CreateModel(
            name='Medicine',
            fields=[
                ('mid', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200)),
                ('price', models.IntegerField()),
            ],
        ),
        migrations.RenameField(
            model_name='customer',
            old_name='id',
            new_name='customerid',
        ),
        migrations.CreateModel(
            name='Stock',
            fields=[
                ('sid', models.AutoField(primary_key=True, serialize=False)),
                ('quantity', models.IntegerField()),
                ('mid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='medical_shop_app.customer')),
            ],
        ),
    ]
