# Generated by Django 3.1.6 on 2021-02-06 15:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medical_shop_app', '0004_auto_20210206_2056'),
    ]

    operations = [
        migrations.AlterField(
            model_name='medicine',
            name='price',
            field=models.CharField(max_length=200),
        ),
    ]
